fix: rate limit during json-ld context loading
eclipse-tractusx/managed-identity-wallet pull request #100
Opened 2023-10-11 07:48 UTC by DominikPinsel

Fix rate limit during json-ld context loading.

Changes
- updated the ssi library to 0.0.17
  - this version supports context caching
- added the most important contexts to MIW
  - so that these contexts are never loaded from the web
- added logging for all incoming http calls
  - it was not possible to see what the MIW was doing on int
- repaired tests
  - added a valid did to a test
  - added a default vc expiry date to test setup

2023-10-12 06:01 UTC, florianrusch-zf requested changes

2023-10-12 06:32 UTC, florianrusch-zf commented
Btw. why is there no GitHub Issue for this?

2023-10-12 06:58 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IssuersCredentialService.java
> +        boolean valid = proofValidation.verifiy(verifiableCredential);
This was fixed in an older version, please recheck @DominikPinsel

2023-10-12 08:32 UTC, DominikPinsel commented on src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java
> +            Mockito.when(mock.verifiy(Mockito.any(VerifiableCredential.class))).thenReturn(true);
This type is part of the library. I could fix it, but then the code won't compile anymore :)

2023-10-12 08:32 UTC, DominikPinsel commented on src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java
> +            Mockito.when(mock.verifiy(Mockito.any(VerifiableCredential.class))).thenReturn(true);
This type is part of the library. I could fix it, but then the code won't compile anymore :)

2023-10-12 08:32 UTC, DominikPinsel commented on src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java
> +            Mockito.when(mock.verifiy(Mockito.any(VerifiableCredential.class))).thenReturn(true);
This type is part of the library. I could fix it, but then the code won't compile anymore :)

2023-10-12 08:32 UTC, DominikPinsel commented on src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java
> +            Mockito.when(mock.verifiy(Mockito.any(VerifiableCredential.class))).thenReturn(false);
This type is part of the library. I could fix it, but then the code won't compile anymore :)

2023-10-12 08:32 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/PresentationService.java
> +        final boolean isValid = linkedDataProofValidation.verifiy(credential);
This type is part of the library. I could fix it, but then the code won't compile anymore :)

2023-10-12 08:35 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/ManagedIdentityWalletsApplication.java
> +    private static final URI URI_SUMMARY_VC_V1 = URI.create("https://catenax-ng.github.io/product-core-schemas/SummaryVC.json");
This is true, but as it is now the Catena-X schemas are stored there. We already addressed that they should be resolved using a real Catena-X domain, but this is not the case today.

2023-10-12 08:43 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/DidDocumentController.java
> +        log.info("Get DID document for bpn: {}", bpn);
Yea, you are right. I used the info level to test something in Hotel Budapest and then forgot to adjust it before creating the PR. Thank you for the review :)

- Updated the log messages of the DidDocumentController
- Set all the log levels to debug for receiving http requests

2023-10-12 08:43 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IssuersCredentialService.java
> +        boolean valid = proofValidation.verifiy(verifiableCredential);
Rechecked. It only compiles if written like this :)

2023-10-12 08:44 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/PresentationService.java
> +            if ((!(e instanceof JwtExpiredException))) {
Yes there is :) Removed one of the outer brackets.

2023-10-12 08:51 UTC, DominikPinsel commented
> Btw. why is there no GitHub Issue for this?

Created Issue #103

2023-10-13 04:55 UTC, florianrusch-zf requested changes

2023-10-13 04:55 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/DidDocumentController.java
> +        log.debug("Received Request to get DID document for identifier: {}", identifier);
Let's keep it consistent
```suggestion
        log.debug("Received request to get DID document for identifier: {}", identifier);
```

2023-10-13 04:55 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/DidDocumentController.java
> +        log.debug("Received Request to get DID document for identifier: {}", bpn);
```suggestion
        log.debug("Received request to get DID document for identifier: {}", bpn);
```

2023-10-13 04:56 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IssuersCredentialService.java
> +        boolean valid = proofValidation.verifiy(verifiableCredential);
Please talk to each other. Within the [PR](https://github.com/eclipse-tractusx/SSI-agent-lib/pull/15) from @borisrizov-zf it got renamed.

2023-10-13 06:49 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IssuersCredentialService.java
> +        boolean valid = proofValidation.verifiy(verifiableCredential);
Here is the code from the main branch in catena-x ng.
https://github.com/eclipse-tractusx/SSI-agent-lib/blob/main/src/main/java/org/eclipse/tractusx/ssi/lib/proof/LinkedDataProofValidation.java

The Tractus-X ssi repository does not release artifacts yet and seems to be in another state.

2023-10-13 07:55 UTC, borisrizov-zf reviewed
lgtm so far, I'll test locally as well and give a final approval.

2023-10-13 07:55 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/ManagedIdentityWalletsApplication.java
> +        RemoteDocumentLoader.getInstance().setEnableLocalCache(true);
Is there actually a mechanism to force update the resources without a PR?

2023-10-13 07:55 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/DidDocumentController.java
> +        log.debug("Received request to get DID document for identifier: {}", bpn);
```suggestion
        log.debug("Received request to get DID document for BPN: {}", bpn);
```

2023-10-13 09:26 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IssuersCredentialService.java
> +        boolean valid = proofValidation.verifiy(verifiableCredential);
@florianrusch-zf yes, the tractus-x repo is up-to-date, but not yet ready to be used as it has no artefact. we'll have to use the catenax-ng repo for a couple PRs before we can finalise and move.

2023-10-13 09:28 UTC, borisrizov-zf commented
This must be merged before #87 as it fixes some issues causing the pipeline to break.

2023-10-13 09:31 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/DidDocumentController.java
> +        log.debug("Received Request to get DID document for identifier: {}", bpn);
As the MIW Is able to resolve DID documents by BPN and DID (in the API called identifier) I assume this is really correct.

2023-10-13 09:33 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/ManagedIdentityWalletsApplication.java
> +        RemoteDocumentLoader.getInstance().setEnableLocalCache(true);
The schemas, we put in the local cache, can only be updated by a PR. I would assume this is ok, as the resources itself should not change once released. An update should happen by publishing a new version.

2023-10-13 09:34 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/DidDocumentController.java
> +        log.debug("Received request to get DID document for identifier: {}", bpn);
The MIW is able to resovle a DID Document By BPN and DID (in the API called identifier). So naming it here identifier is somewhat correct, although confusing.

2023-10-13 12:52 UTC, borisrizov-zf commented
I've given this another thought. I think it won't be wise to implement another level of caching in the MIW. The SSI-Agent-lib already includes a 1 day cache mechanism for the context files, which should be enough. Also using a hard local resource seems unflexible if any changes to the schema happen. Let's shelve this for now.

2023-10-16 08:17 UTC, borisrizov-zf commented
> LGFM, but you (@borisrizov-zf @DominikPinsel) have to decided whether this should be merged or not.

I think we should abandon, because having local copies of the schemas will come back to bite us in the backside, imo.

2023-10-16 09:42 UTC, DominikPinsel commented
> > LGFM, but you (@borisrizov-zf @DominikPinsel) have to decided whether this should be merged or not.
> 
> I think we should abandon, because having local copies of the schemas will come back to bite us in the backside, imo.

So close PR?

2023-10-16 10:17 UTC, borisrizov-zf commented
> > > LGFM, but you (@borisrizov-zf @DominikPinsel) have to decided whether this should be merged or not.
> > 
> > 
> > I think we should abandon, because having local copies of the schemas will come back to bite us in the backside, imo.
> 
> So close PR?

Yeah, close it.

2023-10-16 11:59 UTC, borisuu commented
> Update: Reopen and will just remove the offline resources

Ok, ping me when it's done for review.

2023-10-18 07:08 UTC, DominikPinsel commented
Removed offline loading, squashed changes

@florianrusch-zf @borisrizov-zf FYI

2023-10-18 07:13 UTC, borisrizov-zf approved these changes

2023-10-18 08:03 UTC, borisrizov-zf commented
@florianrusch-zf this is ready for merging. Thanks.

2023-10-18 08:26 UTC, merged

2023-10-19 09:20 UTC, arunsworld commented
> I've given this another thought. I think it won't be wise to implement another level of caching in the MIW. The SSI-Agent-lib already includes a 1 day cache mechanism for the context files, which should be enough. Also using a hard local resource seems unflexible if any changes to the schema happen. Let's shelve this for now.

Nothing in the documentation to indicate that egress to a certain set of URLs is a pre-requisite to run MIW. It's a normal thing that firewalls block egress. You're worried about schema changes not getting picked up? Are we really saying schemas will change without version changing? That in itself is unsettling (left-pad that broke the internet - at least that was build time; this is runtime). MIW is core to all EDC transactions; this looks like an Achilles heel / single point of failure. I hope you reconsider putting this back in or at least having an option to do so. How about starting with a local copy and refreshing on startup and then daily if possible. But no matter what you have something to work with and it's not going to stop the world.

2023-10-19 09:29 UTC, borisrizov-zf commented
> > I've given this another thought. I think it won't be wise to implement another level of caching in the MIW. The SSI-Agent-lib already includes a 1 day cache mechanism for the context files, which should be enough. Also using a hard local resource seems unflexible if any changes to the schema happen. Let's shelve this for now.
> 
> Nothing in the documentation to indicate that egress to a certain set of URLs is a pre-requisite to run MIW. It's a normal thing that firewalls block egress. You're worried about schema changes not getting picked up? Are we really saying schemas will change without version changing? That in itself is unsettling (left-pad that broke the internet - at least that was build time; this is runtime). MIW is core to all EDC transactions; this looks like an Achilles heel / single point of failure. I hope you reconsider putting this back in or at least having an option to do so. How about starting with a local copy and refreshing on startup and then daily if possible. But no matter what you have something to work with and it's not going to stop the world.

The underlying SSI library already adheres to your proposed workflow. We get the resources and cache them for one day. I think it would be reasonable to add static resources when the schemas are in their final state. We're still experiencing changes in those, so makes no sense to update the repo every time there's a change. We might open a task to remind ourselves to add static resources whenever a final version is available.