Fix/did document controller api
eclipse-tractusx/managed-identity-wallet pull request #157
Opened 2023-11-22 13:43 UTC by mustafasalfiti

Seperating the api documentation from the DidDocumentController.java into a seperate file

2023-11-24 08:20 UTC, borisrizov-zf commented
@mustafasalfiti please rebase your local branch using the upstream/develop

2023-11-24 08:45 UTC, mustafasalfiti commented
done

2023-11-28 09:05 UTC, borisrizov-zf requested changes

2023-11-28 09:05 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/apidocs/DidDocumentControllerApiDocs.java
> +                                      "detail": "Wallet not found for BPN BPNL00000000000",
```suggestion
                                      "detail": "Wallet not found for identifier BPNL00000000000",
```

2023-11-28 09:05 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/apidocs/DidDocumentControllerApiDocs.java
> +                                      "title": "Wallet not found for BPN BPNL00000000000",
```suggestion
                                      "title": "Wallet not found for identifier BPNL00000000000",
```

2023-11-28 09:05 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/apidocs/DidDocumentControllerApiDocs.java
> +                                      "detail": "Wallet not found for BPN BPNL00000000000",
```suggestion
                                      "detail": "Wallet not found for identifier BPNL00000000000",
```

2023-11-29 08:49 UTC, mustafasalfiti commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/apidocs/DidDocumentControllerApiDocs.java
> +                                      "detail": "Wallet not found for BPN BPNL00000000000",
Bpn changed to identifier

2023-11-29 13:19 UTC, borisrizov-zf approved these changes

2023-12-01 10:16 UTC, borisrizov-zf commented
@mustafasalfiti hi, you'll have to rebase again as we've pulled changes in with #176. Do this for all your branches - that will fix the pipeline.

2023-12-01 14:50 UTC, merged