Feature: token service and endpoint
eclipse-tractusx/managed-identity-wallet pull request #249
Opened 2024-02-04 18:41 UTC by borisrizov-zf

## Description

This is an implementation of the "/token" endpoint, which is part of the authorized VP flow for resource sharing between EDCs.
Replaces #179 
Closes #139 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-02-06 19:38 UTC, florianrusch-zf requested changes
I'm not fully done with the review

2024-02-06 19:38 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/SecureTokenRequest.java
> +                ", clientSecret='" + clientSecret + '\'' +
I assume, that this method will been used, to write the object to the log, right? If yes, we should avoid, to log the secret.

2024-02-06 19:38 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/SecureTokenRequest.java
> +                ", accessToken='" + accessToken + '\'' +
And maybe also the access token.

2024-02-06 19:38 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IdpAuthorization.java
> +        String idpRootUrl = authServerUrl + "/realms/" + properties.realm();
this could be also done by simply using the [UriComponentsBuilder](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/UriComponentsBuilder.html) from spring. But I guess it doesn't make any big differences.

2024-02-06 19:38 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IdpAuthorization.java
> +        log.debug("OAuth Token request for '{}' during secure token request flow.", secureTokenRequest.getClientId());
```suggestion
        log.debug("Doing OAuth token request for '{}' during secure token request flow.", secureTokenRequest.getClientId());
```

2024-02-06 19:38 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IdpAuthorization.java
> +        assert idpResponse != null;
What happens, if this assertions fails? Will the requester get an 500 response code? Do we see anything in the logs about the problem?

2024-02-06 19:38 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/SecureTokenServiceImpl.java
> +        Instant expirationTime = Instant.now().plus(properties.tokenDuration());
```suggestion
        // IMPORTANT: we re-use the expiration time intentionally to mitigate any kind of timing attacks,
        // as we're signing two tokens.
        Instant expirationTime = Instant.now().plus(properties.tokenDuration());
```

2024-02-06 19:38 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/SecureTokenServiceImpl.java
> +        // as we're signing two tokens.
```suggestion
        // IMPORTANT: we re-use the expiration time intentionally to mitigate any kind of timing attacks,
        // as we're signing two tokens.
        Instant expirationTime = Instant.now().plus(properties.tokenDuration());
```

2024-02-06 19:38 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/SecureTokenServiceImpl.java
> +        Instant expirationTime = Instant.now().plus(properties.tokenDuration());
```suggestion
        // IMPORTANT: we re-use the expiration time intentionally to mitigate any kind of timing attacks,
        // as we're signing two tokens.
        Instant expirationTime = Instant.now().plus(properties.tokenDuration());
```

2024-02-07 13:58 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenController.java
> +    public ResponseEntity<StsTokenResponse> store(
I was experimenting with REST-ful names, but makes no sense in the context of the project. Going to reset it to the old name `token`

2024-02-07 14:01 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/SecureTokenRequest.java
> +                ", clientSecret='" + clientSecret + '\'' +
Yeah, auto-generated, but also never used...

2024-02-08 09:16 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IdpAuthorization.java
> +        assert idpResponse != null;
I actually only added this to make IntelliJ leave me alone 😆
But I'll replace with a normal check and exception.

2024-02-08 09:20 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IdpAuthorization.java
> +        log.debug("OAuth Token request for '{}' during secure token request flow.", secureTokenRequest.getClientId());
Done.

2024-02-08 09:21 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/SecureTokenServiceImpl.java
> +        Instant expirationTime = Instant.now().plus(properties.tokenDuration());
The message doesn't apply here, as the access token was passed from the outside.

2024-02-08 09:22 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/SecureTokenServiceImpl.java
> +        // as we're signing two tokens.
Done

2024-02-08 09:23 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/SecureTokenServiceImpl.java
> +        Instant expirationTime = Instant.now().plus(properties.tokenDuration());
Does not apply to this code, as the access_token is passed from the outside.

2024-02-08 09:23 UTC, borisrizov-zf commented
@florianrusch-zf I pushed the mentioned fixes.

2024-02-08 13:38 UTC, borisrizov-zf commented on src/test/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenControllerTest.java
> +        AuthenticationUtils.setupKeycloakClient("partner", "partner", partnerBpn);
The method body is in the `AuthenticationUtils` class, but basically it builds a keycloak resource and then uses the admin client to persist the resources.

2024-02-08 14:27 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenController.java
> +            throw new InvalidSecureTokenRequest("The provided data could not be used to create and sign a token.");
I'd like to defer this to a later point, as we're going to be implementing some changes to the domain classes, which will make this easier.

2024-02-08 17:56 UTC, florianrusch-zf requested changes

2024-02-08 17:56 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IdpAuthorization.java
> +            throw new InvalidIdpTokenResponse("The idp response cannot be null. Possible causes for this are: the 'clientId' is invalid, the 'client' is not enabled.");
```suggestion
            throw new InvalidIdpTokenResponse("The idp response cannot be null. Possible causes for this are: the 'clientId' is invalid, or the 'client' is not enabled.");
```

2024-02-08 17:56 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/apidocs/SecureTokenControllerApiDoc.java
> +                                      "errorDescription": "The idp response cannot be null. Possible causes for this are: the 'clientId' is invalid, the 'client' is not enabled."
```suggestion
                                      "errorDescription": "The idp response cannot be null. Possible causes for this are: the 'clientId' is invalid, or the 'client' is not enabled."
```

2024-02-08 17:59 UTC, florianrusch-zf commented on src/test/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenControllerTest.java
> +        AuthenticationUtils.setupKeycloakClient("partner", "partner", partnerBpn);
Let's have a quick call maybe tomorrow about it ;-)

2024-02-09 07:29 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenController.java
> +        // todo bri: accept did & bpn
Yes, I actually had a glance at the spec again, the audience should be a did anyway.... I've included both just in case 😄

2024-02-09 07:34 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/IdpAuthorization.java
> +            throw new InvalidIdpTokenResponse("The idp response cannot be null. Possible causes for this are: the 'clientId' is invalid, the 'client' is not enabled.");
Done

2024-02-09 09:17 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/apidocs/SecureTokenControllerApiDoc.java
> +                                      "errorDescription": "The idp response cannot be null. Possible causes for this are: the 'clientId' is invalid, the 'client' is not enabled."
Done

2024-02-12 10:25 UTC, DominikPinsel approved these changes

2024-02-12 10:25 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenController.java
> +        }
Maybe return an error if both parameters all set? I think in this special case we cannot tell what the user intended and might return the wrong token.

2024-02-14 16:02 UTC, DominikPinsel approved these changes

2024-02-14 16:02 UTC, DominikPinsel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/config/security/SecurityConfig.java
> +                        .requestMatchers(new AntPathRequestMatcher("/token", POST.name())).permitAll()
Should we add here some kind of protection now, or do we need to talk about a concept first?

2024-02-19 07:14 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenController.java
> +            @Valid @RequestBody SecureTokenRequest secureTokenRequest
Let's keep it consistent, I'll change to `/api/token`

2024-02-19 07:15 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/SecureTokenRequest.java
> +    private String bearerAccessAlias;
It's part of the spec, so I'd prefer leaving it in.

2024-02-19 07:17 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/exceptions/InvalidIdpTokenResponse.java
> +}
Will do, is more consistent as you suggested.

2024-02-19 09:12 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenController.java
> +        }
Yes, we're throwing an exception from the `assert*` methods, which will note that both parameters are set. The `InvalidSecureTokenRequest`, would be thrown if something within the provided information is invalid. Or do you mean something else?

2024-02-19 09:31 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/SecureTokenRequest.java
> +    private String grantType;
Actually we might have to define a story for this, because Spring supports RFC 7807 since version 3, so we might migrate to a standard `ProblemDetail` error response for the whole MIW. Let's discuss this in a separate issue and leave this as-is for now.
The actual problem here is that the `@NotNull` validation is coming from the Java-side validation and not the json validation, which leads to the usage of the Java property name, not the json property name (this is also validator implementation specific). If we migrate to `ProblemDetail` we'll be able to more concisely define this behavior.

2024-02-20 14:16 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenController.java
> +        }
This exception is probably unnecessary now, since the validator checks for consistency in the `SecureTokenRequest`, but I've decided to leave it in, just in case I've missed something.

2024-02-21 07:36 UTC, borisrizov-zf commented
@DominikPinsel @florianrusch-zf hey, I've pushed a new Validator class for the SecureTokenRequest. Take a look if you're interested in the change, but it's basically the same as before, just in a more modern way.

2024-02-22 08:54 UTC, florianrusch-zf approved these changes

2024-02-22 10:01 UTC, merged