Feat: Create VC as JWT
eclipse-tractusx/managed-identity-wallet pull request #260
Opened 2024-02-27 14:27 UTC by mustafasalfiti

## Description

In the Controllers, an option has been added to generate a VC as a JWT (JSON Web Token). By default, this option is set to false. When set to true, the response will be a JWT containing the VC.

Additionally, certain exception handling has been revised and corrected due to the integration of the new SSI-lib

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-04-19 21:36 UTC, mustafasalfiti commented
should be with the latest ssi agent lib current (main) in order for the tests to work @borisrizov-zf

2024-04-22 06:28 UTC, borisrizov-zf requested changes

2024-04-22 06:28 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/PresentationService.java
> +        SignedJWT presentation = presentationFactory.createPresentation(result.getLeft(), verifiableCredentials, audience, privateKey , "keyId" );
"keyId" passed as string here. Should be the actual keyId.

2024-04-23 09:03 UTC, mustafasalfiti commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/apidocs/IssuersCredentialControllerApiDocs.java
> +                                            "https://cofinity-x.github.io/schema-registry/v1.1/DismantlerVC.json",
link changed to https://eclipse-tractusx.github.io/tractusx-profiles/cx/context/credentials.context.json from our weekly discussion

2024-04-23 16:50 UTC, borisrizov-zf commented
@mustafasalfiti I'll ping you when the new release of the ssi-lib is out, so you can update.

2024-04-24 11:35 UTC, borisrizov-zf reviewed
Just two minor issues to look at.

2024-04-24 11:35 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/IssueDismantlerCredentialRequest.java
> +
This change is unnecessary. You can revert this file.

2024-04-24 11:35 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/CommonService.java
> +            } catch (Exception e) {
This is very broad, can we narrow it down a bit?

2024-04-25 06:03 UTC, borisrizov-zf approved these changes

2024-04-29 19:51 UTC, jjeroch commented on src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java
> +                {"type":"ResiliencyCredential"},
Note, with the new release this type does not exist anymore. From my point of view it does not make sense to follow the old standard - we should rather use the new credentials as per 24.05. release

2024-04-30 07:32 UTC, mustafasalfiti commented on src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java
> +                {"type":"ResiliencyCredential"},
agree on that but in this PR it has nothing to do with the types of the VC, we can create a different PR for it, to fix that in the source code. this test was already there with a JSON-LD reponses, was only recreated to make sure it gives the response as JWT independent of the VC type.

2024-04-30 07:42 UTC, borisrizov-zf commented on src/test/java/org/eclipse/tractusx/managedidentitywallets/vc/HoldersCredentialTest.java
> +                {"type":"ResiliencyCredential"},
Agree, this PR is already large. Please create a new issue, link it here and we'll tackle that next.

On a side note: as soon as the IP check is done, I'll merge.

2024-05-14 07:16 UTC, borisrizov-zf commented
IP check link: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14592
IP check status: Approved

Ready to merge.

2024-05-14 07:20 UTC, borisrizov-zf commented
@mustafasalfiti please rebase to the latest develop version (there was a minor update merged a week ago).

2024-05-15 06:48 UTC, borisrizov-zf commented
@thackerronak Hi, it seems something went wrong with the rebase/merge since now we're getting unwanted changed in the CHANGELOG. Please review and push again.

2024-05-21 06:36 UTC, nitin-vavdiya commented
@borisrizov-zf Rebase is done

2024-05-23 09:54 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/IssueFrameworkCredentialRequest.java
> + public class IssueFrameworkCredentialRequest {
Formatting is off by one space. Please re-check this (and other files), rebase and ping me.

2024-05-23 10:02 UTC, nitin-vavdiya commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/IssueFrameworkCredentialRequest.java
> + public class IssueFrameworkCredentialRequest {
fixed with https://github.com/eclipse-tractusx/managed-identity-wallet/pull/260/commits/697ff85f6cd682d5beac7a75288dce43525b5e50

2024-05-23 11:06 UTC, nitin-vavdiya commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/dto/IssueFrameworkCredentialRequest.java
> + public class IssueFrameworkCredentialRequest {
@borisrizov-zf formatting is done

I think a rebase is not needed as there has been no change in develop branch since the last rebase. Am I right?

2024-05-27 07:19 UTC, borisrizov-zf commented
@nitin-vavdiya Hi, I'm doing manual tests. If all goes well, I'll merge and notify you.

2024-05-28 08:47 UTC, merged

2024-05-28 09:31 UTC, borisrizov-zf commented
Dash review required
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14889