Feature: Make self-issued tokens one-time-use only
eclipse-tractusx/managed-identity-wallet pull request #268
Opened 2024-03-06 09:08 UTC by aleksandra-bel

This is implementation of Make self-issued tokens one-time-use only
Closes: https://github.com/eclipse-tractusx/managed-identity-wallet/issues/264

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-03-06 12:17 UTC, borisrizov-zf requested changes
Looks good. Just add the liquibase comments and test it.

2024-03-06 12:17 UTC, borisrizov-zf commented on src/main/resources/db/changelog/changes/create_jti_table.sql
> +
Add the liquibase required comments:
```
-- liquibase formatted sql
-- changeset andreibogus:create-jti-table
```

2024-03-06 14:16 UTC, andreibogus commented on src/main/resources/db/changelog/changes/create_jti_table.sql
> +
Done in [9b277d7](https://github.com/eclipse-tractusx/managed-identity-wallet/pull/268/commits/9b277d7fe00aab4ab215eb3f91896d3429daffae)

2024-03-06 15:23 UTC, borisrizov-zf approved these changes
I'll test locally and merge afterwards. Look good!

2024-03-07 11:50 UTC, borisrizov-zf approved these changes
Doing local tests, and will merge afterwards.

2024-03-07 13:14 UTC, borisrizov-zf requested changes
Found a bug when re-wrapping an access token.

2024-03-07 14:02 UTC, andreibogus commented
Fixes for re-wrapping an access token applied in [e047550](https://github.com/eclipse-tractusx/managed-identity-wallet/pull/268/commits/e04755016aecdf6d6ade0eebae065f36ce80d429)

2024-03-07 14:13 UTC, borisrizov-zf approved these changes
Looks good, I'll do the manual tests and ping you if anything arises.

2024-03-07 14:45 UTC, merged