Feature/support es256 k
eclipse-tractusx/managed-identity-wallet pull request #274
Opened 2024-03-14 12:01 UTC by aleksandra-bel

This is implementation of Support ES256K/secp256k1
Closes: https://github.com/eclipse-tractusx/managed-identity-wallet/issues/266

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-03-15 11:46 UTC, borisrizov-zf requested changes

2024-03-15 12:17 UTC, aleksandra-bel commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/service/JwtPresentationES256KService.java
> +                JWSHeader header = new JWSHeader(algorithm, type, null, null, null, null, null, null, null, null, issuer, true, null, null);
With the builder it looks much better, fixed [541a524](https://github.com/eclipse-tractusx/managed-identity-wallet/pull/274/commits/541a524646b26910d19648f800931d54d549146e)

2024-03-15 13:17 UTC, borisrizov-zf approved these changes
Looks good, will merge after manual tests pass.

2024-03-19 09:28 UTC, borisrizov-zf commented
@aleksandra-bel @andreibogus 
Ok, I found something. We have to add the new key to the DID document.

2024-03-19 09:38 UTC, borisrizov-zf requested changes
Update DID document, adding the newly issued key to the list of verificationMethod.

2024-03-20 10:40 UTC, andreibogus commented
added WalletKey for ES256K algorithm to DidDocument

2024-03-20 12:21 UTC, borisrizov-zf approved these changes
Ok this time I think we're done 😆 
Doing manual sweep and I'll merge when I'm done with that.

2024-03-21 08:04 UTC, borisrizov-zf requested changes

2024-03-21 08:04 UTC, borisrizov-zf commented
@andreibogus @aleksandra-bel some minor findings.

2024-03-21 08:57 UTC, borisrizov-zf approved these changes

2024-03-21 09:12 UTC, merged