Fix/security finding
eclipse-tractusx/managed-identity-wallet pull request #277
Opened 2024-03-28 11:25 UTC by thackerronak

## Description
Spring boot land cloud lib version was updated to mitigate https://github.com/advisories/GHSA-f3jh-qvm4-mg39

Note: 
Below are two dependencies showing restricted which need to be fixed in ssi-lib. 
maven/mavencentral/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.9.23, None, restricted, #14188
maven/mavencentral/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.9.23, None, restricted, #14185

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-04-12 06:58 UTC, borisrizov-zf commented
@thackerronak Hi, we cannot merge a PR which includes "restricted" dependencies. You also mentioned that this has to do with the SSI lib. Can you elaborate?

2024-04-12 07:57 UTC, thackerronak commented
> @thackerronak Hi, we cannot merge a PR which includes "restricted" dependencies. You also mentioned that this has to do with the SSI lib. Can you elaborate?

@borisrizov-zf I have updated the DEPENDENCIES file and found that all dependencies are showing approved.

2024-05-27 06:34 UTC, nitin-vavdiya approved these changes

2024-05-27 06:36 UTC, nitin-vavdiya requested changes

2024-05-27 06:36 UTC, nitin-vavdiya commented on gradle.properties
> -springCloudVersion=2022.0.3
Please add license header

2024-05-28 04:28 UTC, nitin-vavdiya approved these changes

2024-07-05 08:46 UTC, nitin-vavdiya commented
@thackerronak  Please rebase and re-generate DEPENDENCIES

2024-07-22 06:31 UTC, nitin-vavdiya commented
@thackerronak  please rebase and  re-generate DEPENDENCIES

2024-07-22 11:34 UTC, closed without merging