Feature/bpn auth validation
eclipse-tractusx/managed-identity-wallet pull request #282
Opened 2024-04-08 12:23 UTC by andreibogus

This is implementation of Feature: BPN authorisation validation
Closes: https://github.com/eclipse-tractusx/managed-identity-wallet/issues/278

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-04-11 09:30 UTC, borisrizov-zf requested changes

2024-04-11 09:57 UTC, andreibogus commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/constant/StringPool.java
> +    public static final String BPN_NOT_FOUND = "Invalid token, BPN not found";
Done

2024-04-15 07:07 UTC, borisrizov-zf approved these changes

2024-05-02 07:14 UTC, borisrizov-zf commented
@andreibogus @aleksandra-bel please rebase, hopefully DAST will stop whining.

2024-05-27 07:01 UTC, nitin-vavdiya commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/config/security/CustomAuthenticationEntryPoint.java
> +        response.addHeader("WWW-Authenticate", wwwAuthenticate);
maybe we can use constant from class `org.springframework.http.HttpHeaders`

2024-07-29 09:18 UTC, nitin-vavdiya commented
Closing this is PR as there has been no update from the author for a long time.

2024-07-29 09:21 UTC, closed without merging