Abstract key storage and signing operations to facilitate different key storage types
eclipse-tractusx/managed-identity-wallet pull request #285
Opened 2024-04-15 08:47 UTC by PManaras

This PR introduces support for implementing different types of keystorages via the newly KeyProvider interface. This interface can be used to retrieve keys from different types of storages, i.e. remote vaults, file-system, database.

The newly created SigningService can be used to implement different types of signature processes. The standard signature process is "LOCAL" meaning the MIW will use keys provided by the keyprovider to sign VP/VC locally.

This PR also adds to new properties to application.yaml (authoritySigningServiceType (defaults to "LOCAL), localSigningKeyStorageType (defaults to DB). These additions are also reflected in the corresponding env-files.

The database entity Wallet was updated and now contains a new field signingServiceType that reflects which wallet uses which signatureServices. The new field is introduced via a new database migration (v3) and sets the signing_service_type to "LOCAL" for all existing wallets. This means: with the standard configuration the MIW will act as before.

this PR includes changes made in the [PR on the main-branch](https://github.com/eclipse-tractusx/managed-identity-wallet/pull/276)

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-04-24 12:18 UTC, borisrizov-zf requested changes
Looks good, just these minor issues.

2024-04-24 12:18 UTC, borisrizov-zf commented on src/main/resources/db/changelog/changes/init.sql
> +ALTER TABLE public.wallet ADD signing_service_type VARCHAR(255) NOT NULL DEFAULT 'LOCAL';
Add one empty line at the end to avoid the next changeset appearing as a modification instead of an addition.

2024-04-24 12:18 UTC, borisrizov-zf commented on src/test/resources/application-test.yaml
> +debug: true
Missing new line at end of file.

2024-04-24 12:18 UTC, borisrizov-zf commented on src/test/resources/db/changelog/changes/add-signing-service-column.sql
> +ALTER TABLE public.wallet ADD signing_service_type VARCHAR(255) NOT NULL DEFAULT 'LOCAL';
Missing new line at end of file.

2024-04-24 12:18 UTC, borisrizov-zf commented on src/test/resources/db/changelog/changes/without-changes-init.sql
> +ALTER TABLE public.wallet_key ADD key_id varchar(255) NULL;
Missing new line at end of file.

2024-04-25 06:56 UTC, PManaras commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/controller/SecureTokenController.java
> +    }
removed it, as this is in fact not needed

2024-04-25 07:10 UTC, PManaras commented on CHANGELOG.md
> +
actually, i don't see these chnages in the local file. it seems, that the dependabot in the cofinity repo adds these changes

2024-04-25 07:37 UTC, closed without merging