Pr upstream keystorage
eclipse-tractusx/managed-identity-wallet pull request #291
Opened 2024-04-25 07:37 UTC by PManaras

This PR introduces support for implementing different types of keystorages via the newly KeyProvider interface. This interface can be used to retrieve keys from different types of storages, i.e. remote vaults, file-system, database.

The newly created SigningService can be used to implement different types of signature processes. The standard signature process is "LOCAL" meaning the MIW will use keys provided by the keyprovider to sign VP/VC locally.

This PR also adds to new properties to application.yaml (authoritySigningServiceType (defaults to "LOCAL), localSigningKeyStorageType (defaults to DB). These additions are also reflected in the corresponding env-files.

The database entity Wallet was updated and now contains a new field signingServiceType that reflects which wallet uses which signatureServices. The new field is introduced via a new database migration (v3) and sets the signing_service_type to "LOCAL" for all existing wallets. This means: with the standard configuration the MIW will act as before.

this PR includes changes made in the [PR on the main-branch](https://github.com/eclipse-tractusx/managed-identity-wallet/pull/276)

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

This PR is qual to [PR285](https://github.com/eclipse-tractusx/managed-identity-wallet/pull/285) from a different merge source

2024-04-25 07:54 UTC, borisrizov-zf reviewed
Two minor changes needed due to divergence in source branches, after that we will wait for the IP check approval.

2024-04-25 07:54 UTC, borisrizov-zf commented on CHANGELOG.md
> -
Re-add this line, as it is present in our version of the develop branch.

2024-04-25 07:54 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/ManagedIdentityWalletsApplication.java
> - *  Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
Revert to 2023 in this file, as nothing else has changed.

The date is only changed in modified files.

2024-05-27 08:42 UTC, nitin-vavdiya commented
License headers need to be updated in the changed file

2024-05-28 12:42 UTC, borisrizov-zf commented
@thackerronak @nitin-vavdiya We're ok to rebase this branch and do final testing before we merge.

2024-05-28 12:44 UTC, nitin-vavdiya commented
> @thackerronak @nitin-vavdiya We're ok to rebase this branch and do final testing before we merge.

Rebase is done, fixing failing test cases, will let  you know once it is ready to merge

2024-05-29 09:02 UTC, borisrizov-zf requested changes

2024-05-29 09:08 UTC, nitin-vavdiya commented on src/main/java/org/eclipse/tractusx/managedidentitywallets/dao/repository/WalletKeyRepository.java
> +     * @param id        the id param algorithm the algorithm
fixed with: https://github.com/eclipse-tractusx/managed-identity-wallet/pull/291/commits/fcf86af9177afa6d516b34367a45d6ab02214eaf

2024-05-29 09:14 UTC, nitin-vavdiya commented on CHANGELOG.md
> +* add asJwt as query param and fix
This is merge commit I think after rebase

2024-06-03 12:38 UTC, merged