Miw 1 july 2023
eclipse-tractusx/managed-identity-wallet pull request #31
Opened 2023-07-13 13:21 UTC by DominikPinsel

This PR contain all changes from https://github.com/catenax-ng/tx-managed-identity-wallets since the 1st of July.

2023-07-14 06:58 UTC, mknoopvw commented
Adds all increments and progress made since the initial PR has been issued.

No reason not to merge from my point of view.

Yet I do not know what the Eclipse Foundation's point of view is.

2023-07-17 07:59 UTC, carslen commented
Please add a committer as a reviewer as long as you do not have a committer in your dev team if you want to get your stuff merged. :)

2023-07-17 08:11 UTC, carslen requested changes
Please update `DEPENDENCIES` file, please refer to my comment.

2023-07-17 08:11 UTC, carslen commented on DEPENDENCIES
I'm a bit confused about this `DEPENDECIES` file. If I check your the branch from your fork (where this PR comes from) and run the Eclipse DASH tool using gradle, a different `DEPENDENCIES` file is the result. Please update the file.

2023-07-17 14:05 UTC, mknoopvw commented
@DominikPinsel how much will have to be adjusted to make this PR ready to be merged?

2023-07-18 08:40 UTC, DominikPinsel commented
> @DominikPinsel how much will have to be adjusted to make this PR ready to be merged?

I assume not much :)

2023-07-18 08:42 UTC, DominikPinsel commented on DEPENDENCIES
This is really strange. I update the DEPENDENCIES file using a script.

```sh
#!/bin/bash

# download the latest version of the Eclipse Dash License tool
curl --output org.eclipse.dash.licenses.jar \
    https://repo.eclipse.org/service/local/repositories/dash-licenses-snapshots/content/org/eclipse/dash/org.eclipse.dash.licenses/1.0.3-SNAPSHOT/org.eclipse.dash.licenses-1.0.3-20230714.055026-52.jar


# update DEPENDENCIES file
./gradlew dependencies | grep -Poh "(?<=\s)[\w\.-]+:[\w\.-]+:[^:\s]+" | grep -v "^org\.eclipse" | sort | uniq |
    java -jar org.eclipse.dash.licenses.jar -summary DEPENDENCIES - |
    grep restricted
```

I just run the script again and got the same dependencies file :confused:

2023-07-18 08:59 UTC, carslen approved these changes

2023-07-18 09:00 UTC, merged