Chore!: remove not needed apis and summary vc support
eclipse-tractusx/managed-identity-wallet pull request #315
Opened 2024-06-12 07:09 UTC by nitin-vavdiya

## Remove not needed API and summary VC support
### What
1. Issue BPN credentials API is removed 
2. Issue Membership credential API is removed
3. Issue Framework credential API is removed
4. Summary credential support is removed
5. Test cases modification 

### Why
In the new release of tractus-X , we have a new Issuer component and all VC formation(VS JSON structure) will be taken case by this component

The responsibility of MIW is now to sign VC provided by the issuer component only. 

EDC is using IATP protocol instead of summary VC
 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-06-12 11:20 UTC, borisuu requested changes

2024-06-12 11:20 UTC, borisuu commented on docs/api/openapi_v001.json
Why is this file changed?

2024-06-12 11:21 UTC, borisrizov-zf requested changes

2024-06-12 11:21 UTC, borisrizov-zf commented on docs/api/openapi_v001.json
Why is this file changed?

2024-06-12 11:23 UTC, nitin-vavdiya commented on docs/api/openapi_v001.json
We removed 3 APIs and DTOs so I thought we also need to remove API specification

2024-06-13 06:37 UTC, borisrizov-zf commented on docs/api/openapi_v001.json
True, but the formatting seems off, too many lines are changed. Could you check that.

2024-06-13 07:10 UTC, nitin-vavdiya commented on docs/api/openapi_v001.json
fixed with : https://github.com/eclipse-tractusx/managed-identity-wallet/pull/315/commits/b10fa38eeae221b48adc6ebdace8ffdf4781bb09

2024-06-13 10:56 UTC, borisrizov-zf approved these changes

2024-06-13 10:57 UTC, merged