Miw 26 july 2023
eclipse-tractusx/managed-identity-wallet pull request #38
Opened 2023-07-26 10:08 UTC by DominikPinsel

---
name: Pull Request Template
about: 'template for PRs that ensures basic information is provided'
title: '(feat|fix|chore|doc): _description of introduced change_'
---

## Description

Thanks for opening this contribution!
_What does this PR introduce? Does it fix a bug? Does it add a new feature? Is it enhancing documentation?_

Fixes # (issuenumber from PR destination repo)

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up to date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] Copyright and license header are present on all affected files

### Additional information

- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if you are unsure, who to contact, or if want to engage in a general discussion
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation contribution guidelines](https://www.eclipse.org/projects/handbook/#contributing)

2023-07-26 11:33 UTC, DominikPinsel commented
@carslen I cannot add you as reviewer myself, but maybe you can have a look :) CI pipeline is now running again and the DEPENDENCIES file updated.

2023-07-26 11:40 UTC, carslen commented
> @carslen I cannot add you as reviewer myself, but maybe you can have a look :) CI pipeline is now running again and the DEPENDENCIES file updated.

I've added you as a contributor to Eclipse-Tractusx: https://projects.eclipse.org/projects/automotive.tractusx/who

As of now you should be able to select reviewers in PRs.

2023-07-26 12:20 UTC, carslen requested changes
Added some comments.

2023-07-26 12:20 UTC, carslen commented on charts/managed-identity-wallet/ci/all-values.yaml
Can you explain the purpose and usage of this file?

2023-07-26 12:20 UTC, carslen commented on charts/managed-identity-wallet/values.yaml
>    repository: ghcr.io/catenax-ng/tx-managed-identity-wallets_miw_service
Using this container registry/package is not allowed. Please publish your container image at Docker Hub (TRG 4.05 - Container Registries).

2023-07-26 12:20 UTC, carslen commented on charts/managed-identity-wallet/values.yaml
>    - name: acr-credential
Why addressing a imagePullSecret?

2023-07-26 12:20 UTC, carslen commented on charts/managed-identity-wallet/values.yaml
>      password: postgres
Why hard coding "dummypasswords" instead of rely on postgresql random password creation? Same question for line 153.

2023-07-26 12:52 UTC, DominikPinsel commented on charts/managed-identity-wallet/ci/all-values.yaml
The values in this file are used by the chart tests in `charts/managed-identity-wallet/tests`. The `ci` folder naming is somewhat misleading.

2023-07-26 12:53 UTC, DominikPinsel commented on .github/workflows/service-build.yaml
>            tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest${{ env.TAG_SUFFIX }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}.${{ env.SHORT_SHA }}, ${{ env.REGISTRY }}/${{ e
I will remove the whole CI workflow for now. As there is already an open issue to do the docker hub release, this is a good opportunity to do it in a separate PR.

2023-07-26 12:55 UTC, DominikPinsel commented on charts/managed-identity-wallet/values.yaml
>    repository: ghcr.io/catenax-ng/tx-managed-identity-wallets_miw_service
replaced repository with `tractusx/managed-identity-wallet`

2023-07-26 12:56 UTC, DominikPinsel commented on charts/managed-identity-wallet/values.yaml
>    - name: acr-credential
True. Removed the secret.

2023-07-26 12:58 UTC, DominikPinsel commented on charts/managed-identity-wallet/values.yaml
>      password: postgres
True. As there are probably different things, that can be improved, I would like to solve this in a separate issue. I hope this is fine
https://github.com/eclipse-tractusx/managed-identity-wallet/issues/40

2023-07-26 14:28 UTC, carslen approved these changes
For upcoming PRs, please use way more smaller PRs! For now I'll accept this bigger PR. Separate i.e. changes on workflows and code in different PRs. We like to have smaller but more often PRs :)

Let me know if I shall merge the PR.

2023-07-27 11:49 UTC, pmoscode commented on charts/managed-identity-wallet/ci/all-values.yaml
I can give explanation for that:
This folder is required by this GH Action: "helm/chart-testing-action". You cannot provide a "custom-values.yaml" via cli, but you have to do it with this folder... For whatever reason...

2023-07-27 12:02 UTC, carslen commented on charts/managed-identity-wallet/ci/all-values.yaml
Thanks for clarification.

2023-07-27 12:48 UTC, merged