chore: update or pin action versions, workflow naming and action's config
eclipse-tractusx/managed-identity-wallet pull request #81
Opened 2023-09-07 09:09 UTC by pmoscode

## Description

This is a complete check of all GH workflows. What was checked and updated:
- Workflow naming 
- action's version (and config when required)
- workflow's agent
- trigger branch names

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-09-08 14:50 UTC, the-tatanka approved these changes
LGTM

2023-10-04 10:59 UTC, carslen requested changes

2023-10-04 10:59 UTC, carslen commented on .github/workflows/veracode.yaml
> +        uses: gradle/gradle-build-action@v2Ï
This version (`v2Ï`) looks like a typo.

2023-10-04 11:27 UTC, pmoscode commented on .github/workflows/veracode.yaml
> +        uses: gradle/gradle-build-action@v2Ï
Yep, was a typo...

2023-10-04 11:28 UTC, carslen approved these changes
LGTM

2023-10-04 11:28 UTC, merged