chore: update git-changelog regex pattern for version finding
eclipse-tractusx/managed-identity-wallet pull request #82
Opened 2023-09-07 13:09 UTC by pmoscode

## Description

The task to generate the Changelog is updated:
1. Now, it does not delete the Changelog everytime before creation
2. It does the Changelog update inline. -> So that manual editings are not lost. 

Additionally the regex to find the current / latest version in the Changelog is updated. 
It wouldn't have worked due to changes in the Changelog template (CHANGELOG.md.jinja)

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-09-07 13:10 UTC, pmoscode commented
@borisrizov-zf 
Please review

2023-09-07 13:16 UTC, mknoopvw approved these changes

2023-09-07 13:17 UTC, mknoopvw commented
Nonetheless, let's hope that there will not emerge a plethora of ways to communicate a version of MIW.

2023-09-12 08:08 UTC, DominikPinsel approved these changes

2023-09-12 08:32 UTC, borisrizov-zf requested changes

2023-09-12 08:32 UTC, borisrizov-zf commented on Taskfile.yaml
> +      - git-changelog -i -g '^## (?P<version>[v|V]?\d+\.\d+\.\d+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?)' -o CHANGELOG.md -c conventional -t path:./CHANGELOG.m
Please add a comment detailing the regex. It's long and the intent is not immediately obvious, e.g.:
(?P<version>[v|V]?\d+\.\d+\.\d+) - semantic version capturing group
-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)* - optional pre-release candidates and build info, e.g. -rc.3
(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)? - optional build metadata
etc..

2023-09-18 09:46 UTC, pmoscode commented on Taskfile.yaml
> +      - git-changelog -i -g '^## (?P<version>[v|V]?\d+\.\d+\.\d+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?)' -o CHANGELOG.md -c conventional -t path:./CHANGELOG.m
@borisrizov-zf 
Added explanation. Please check.

2023-09-18 10:09 UTC, borisrizov-zf approved these changes

2023-09-18 12:18 UTC, pmoscode commented
Hi @SebastianBezold,
can you merge this PR?

Thx

2023-09-25 08:14 UTC, borisrizov-zf commented
@pmoscode Sebastian is away for 5 weeks, so we'll have to ping someone else.

@scherersebastian can you take a look?

2023-09-28 08:10 UTC, borisrizov-zf commented
@carslen Hi can you merge this?

2023-10-04 11:00 UTC, carslen approved these changes

2023-10-04 11:00 UTC, merged