Features/argo cd dev
eclipse-tractusx/managed-identity-wallet pull request #87
Opened 2023-09-14 06:37 UTC by DominikPinsel

Some changes I would like to apply for an continuous Hotel Budapest deployment.
I'm still trying things out, so draft state.

2023-09-14 08:15 UTC, mknoopvw commented on charts/managed-identity-wallet/values.yaml
> +    hosts:  []
@DominikPinsel please remove the additional white space

2023-09-18 11:00 UTC, pmoscode commented on .github/workflows/release.yml
> +            type=semver,pattern={{major}}.{{minor}}
"latest" is missing

2023-09-28 12:09 UTC, DominikPinsel commented on charts/managed-identity-wallet/values.yaml
> +    hosts:  []
done :)

2023-09-29 05:09 UTC, borisrizov-zf commented
@DominikPinsel please do an interactive rebase and fix commit text, squash any "wip" commits etc.

2023-09-29 06:51 UTC, DominikPinsel commented
> @DominikPinsel please do an interactive rebase and fix commit text, squash any "wip" commits etc.

Sure. These are all test commits to trigger the CI pipeline in my fork. Will create a single commit before I ask for the actual merge here :)

2023-10-04 11:06 UTC, carslen commented
I've marked the PR as draft as it looks like @DominikPinsel is still testing triggering workflows. Please use more descriptive commit messages. As you've finished testing, please remove draft from this PR.

2023-10-06 12:11 UTC, borisrizov-zf approved these changes

2023-10-10 08:42 UTC, borisrizov-zf commented
@DominikPinsel please rebase

2023-10-12 07:03 UTC, borisrizov-zf commented
@DominikPinsel @carslen let's wait for the merge of the test fix #100, rebase and check the runner time again.

2023-10-12 08:25 UTC, DominikPinsel commented
ToDo for me: Update Dependencies file as well, and check content

2023-10-12 11:58 UTC, DominikPinsel commented
@carslen Build is now running green :) feel free to merge

2023-10-13 08:45 UTC, pmoscode commented
From my point of view these things are missing:

1. Recerate the Helm chart Readme
2. Carrying out basic checks. Regarding the TRG's. (Folder structure, required files)
3. check if DEPENDENCIES file has no "restricted" or "rejected" libs
4. Perform Helm chart unittests
5. Perform Helm chart upgrade test

Some of these points may be implemented later, but I guess, point 1, 2, 3 and 4 are quick wins and easy to implement (some actions are already there, so they just have to be executed).

And point 5 is required and issued here: https://github.com/eclipse-tractusx/managed-identity-wallet/issues/69

2023-10-13 08:56 UTC, borisrizov-zf requested changes

2023-10-13 08:56 UTC, borisrizov-zf commented on DEPENDENCIES
> +maven/mavencentral/love.forte.simbot/simbot-logger-jvm/3.3.0, , restricted, clearlydefined
Rebase branch and run 'dashLicenseCheck' again.

2023-10-13 09:00 UTC, DominikPinsel commented on DEPENDENCIES
> +maven/mavencentral/love.forte.simbot/simbot-logger-jvm/3.3.0, , restricted, clearlydefined
working on it ;)

2023-10-13 09:24 UTC, borisrizov-zf requested changes

2023-10-13 09:24 UTC, borisrizov-zf commented on build.gradle
> +    implementation 'org.eclipse.tractusx.ssi:cx-ssi-lib:0.0.16'
We should consider merging #100 first and then this one

2023-10-13 11:55 UTC, pmoscode requested changes

2023-10-16 06:05 UTC, borisrizov-zf commented on .gitignore
> +org.eclipse.dash.licenses-1.0.3-*.jar
This isn't even needed any more, as we've already merged the dash license gradle task. I suppose this can be removed.

2023-10-16 06:06 UTC, borisrizov-zf commented on scripts/update_dependencies_file.sh
> +update DEPENDENCIES file
File is removed.

2023-10-16 09:27 UTC, DominikPinsel commented on .releaserc
> +        "prepareCmd": "sed -i  's/appVersion:.*/appVersion: ${nextRelease.version}/g' ./charts/managed-identity-wallet/Chart.yaml"
The Chart Version is not changed automatically. Doing this using the SemanticVersioning tool does not work, so I assume we have to maintain the Chart Version manually atm.

2023-10-16 11:24 UTC, borisrizov-zf commented
@DominikPinsel please rebase as we've merged some changes for the dash license check. afterwards we can finish the PR, I think.

2023-10-17 05:43 UTC, florianrusch-zf requested changes

2023-10-17 05:43 UTC, florianrusch-zf commented on .github/workflows/release.yml
> +        githubUserName
Is this line correct?

2023-10-17 05:43 UTC, florianrusch-zf commented on charts/managed-identity-wallet/values.yaml
>    extraEnvVars:
```suggestion
  extraEnvVars: []
```

2023-10-18 07:56 UTC, DominikPinsel commented on .releaserc
> +    "main",
This should be main. If we write it like this the semantic release creates releases from the main branch, and pre-releases from the develop branch (would be the next two lines in .releaserc)

2023-10-18 08:28 UTC, florianrusch-zf commented on build.gradle
> +    implementation 'org.eclipse.tractusx.ssi:cx-ssi-lib:0.0.16'
Double check after rebase

2023-10-18 10:03 UTC, borisrizov-zf approved these changes

2023-10-18 10:56 UTC, pmoscode approved these changes

2023-10-18 11:01 UTC, merged