Feature/app test coverage action
eclipse-tractusx/managed-identity-wallet pull request #94
Opened 2023-09-22 13:16 UTC by pmoscode

## Description

This PR adds a GH Action workflow to test the MIW app. (Java Jacoco tests)
The results will be added to the GH Action run.

Beside that, the test code coverage will also be reported as a summary inside the GH Action run.
If the run is triggered by a PR, it will also attache the coverage summary to the PR as a comment.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-09-25 08:25 UTC, mknoopvw approved these changes

2023-10-04 11:12 UTC, carslen requested changes

2023-10-04 11:12 UTC, carslen commented on .github/workflows/app-test-coverage.yml
> +# * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
As this is a new file, copyright cannot start in the past.

2023-10-04 11:29 UTC, pmoscode commented on .github/workflows/app-test-coverage.yml
> +# * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
Header updated

2023-10-04 11:29 UTC, carslen approved these changes
LGTM

2023-10-04 11:30 UTC, merged