feat(helm): Make liveness & readiness probes configurable
eclipse-tractusx/managed-identity-wallet pull request #99
Opened 2023-10-09 05:01 UTC by florianrusch-zf

## Description

Make readiness & liveness probes configurable

Closes #98 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-10-10 05:48 UTC, florianrusch-zf commented on charts/managed-identity-wallet/README.md
> +![Version: 0.1.0](https://img.shields.io/badge/Version-0.1.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![App
Is this version change okay? How are chart version bumps are handled? With each change? With each release? @DominikPinsel

2023-10-10 05:48 UTC, florianrusch-zf commented on charts/managed-identity-wallet/README.md
> +| miw.ssi.enforceHttpsInDidWebResolution | bool | `true` | Enable to use HTTPS in DID Web Resolution |
I didn't changed that. Is this change okay @DominikPinsel ?

2023-10-11 12:27 UTC, DominikPinsel commented on charts/managed-identity-wallet/README.md
> +![Version: 0.1.0](https://img.shields.io/badge/Version-0.1.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![App
I would go with AppVersion `0.1.1` at the moment :) This is the latest released image. This version should then be incremented with each release of a new image.

I don't think there is a automated way to update Chart Versions, as I assume it strongly depends on the kind of changes in the Chart itself and there is a good chance, that a Chart Version bump might not be necessary between releases (if done right). But maybe I'm wrong.

2023-10-11 12:29 UTC, DominikPinsel commented on charts/managed-identity-wallet/README.md
> +| miw.ssi.enforceHttpsInDidWebResolution | bool | `true` | Enable to use HTTPS in DID Web Resolution |
Yes, this should be enabled by default. This might cause problems for local runs (where http calls can be done inside the kubernetes), but let's ignore it for now. There are other settings where we have this problem (with or without ingress/https/etc) as well.

2023-10-11 12:31 UTC, DominikPinsel approved these changes
Thank you very much for contributing to the MIW as well! :) I know you are often very busy and we really appreciate your contribution here a lot.

2023-10-12 06:09 UTC, florianrusch-zf commented
@DominikPinsel @borisrizov-zf  I don't know the working model for this repo? Should this been merged to main or develop branch?

2023-10-12 07:01 UTC, borisrizov-zf commented
> @DominikPinsel @borisrizov-zf I don't know the working model for this repo? Should this been merged to main or develop branch?

Please merge into develop.

2023-10-12 07:27 UTC, florianrusch-zf commented on charts/managed-identity-wallet/README.md
> +![Version: 0.1.0](https://img.shields.io/badge/Version-0.1.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![App
@DominikPinsel @borisrizov-zf should I increase the app version or not?

2023-10-12 09:45 UTC, borisrizov-zf commented on charts/managed-identity-wallet/README.md
> +![Version: 0.1.0](https://img.shields.io/badge/Version-0.1.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![App
I think we should always sync the two versions.

2023-10-13 07:44 UTC, DominikPinsel commented on charts/managed-identity-wallet/README.md
> +![Version: 0.1.0](https://img.shields.io/badge/Version-0.1.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![App
> @DominikPinsel @borisrizov-zf should I increase the app version or not?

The AppVersion = Container Image Version by default. So we should increase the chart version. where I would go with the minor :)

2023-10-13 08:51 UTC, borisrizov-zf approved these changes

2023-10-13 12:44 UTC, pmoscode commented on charts/managed-identity-wallet/templates/deployment.yaml
> +          {{- with .Values.livenessProbe }}
A small question:
Why should it be possible to disable the readiness and liveness probe?

2023-10-16 07:50 UTC, florianrusch-zf commented on charts/managed-identity-wallet/templates/deployment.yaml
> +          {{- with .Values.livenessProbe }}
For example if you want to debug into the pod on bootup the java process would wait until the debugger connected successfully which could take some time. Or you debug into the running pod and create a breakpoint somewhere to fetch a request, then the whole application would be blocked by this eventually, which would lead to failing probes and k8s terminates the pod, while you are debugging 😉

Please resolve this conversations, if everything got clarified 🙂

2023-10-16 07:52 UTC, florianrusch-zf commented
I bumped the chart version, but not the appVersion. This should be done in a new PR in my opinion.

2023-10-16 08:06 UTC, borisrizov-zf approved these changes

2023-10-18 08:25 UTC, pmoscode commented on charts/managed-identity-wallet/templates/deployment.yaml
> +          {{- with .Values.livenessProbe }}
Ok, from this perspective, it might be helpful.

2023-10-18 08:25 UTC, pmoscode approved these changes

2023-10-18 10:04 UTC, borisrizov-zf commented
I'd say merge after #87 is merged.

2023-10-18 12:13 UTC, borisrizov-zf approved these changes

2023-10-18 12:40 UTC, pmoscode requested changes

2023-10-18 12:40 UTC, pmoscode commented on .github/workflows/chart-lint-test.yml
> +  verify-helm-docs:
Why do we verify helm docs inside a "linting" and "testing" workflow? I don't expect it here.

Either  we rename the workflow to something like "chart-lint-test-verify.yaml" (and also the "name" attribute) or the "verify" action is executed separately (ex. "chart-check-condition.yaml" or "chart-check-state.yaml").

2023-10-18 12:40 UTC, pmoscode commented on .github/workflows/chart-lint-test.yml
> +      - uses: actions/checkout@v4
Id would like to provide the "name" property here (and in the subsequent steps) for easier understanding.
To answer: "What is this step doing?"

2023-10-27 10:28 UTC, borisrizov-zf commented
@florianrusch-zf what is the status on these?

2023-11-02 10:36 UTC, borisrizov-zf commented
@florianrusch-zf ping

2023-11-09 08:25 UTC, florianrusch-zf commented on .github/workflows/chart-lint-test.yml
> +  verify-helm-docs:
@pmoscode what do you think about renaming this workflow to "chart-verification.yaml" and the `name` to "Verify and Test Helm Chart"

2023-11-09 08:34 UTC, florianrusch-zf commented on .github/workflows/chart-lint-test.yml
> +      - uses: actions/checkout@v4
Fixed :-)

2023-11-09 08:38 UTC, florianrusch-zf commented
@borisrizov-zf @DominikPinsel I need help again with adjusting the chart version :D 

I got the following merge conflict.
```diff
<<<<<<< feat/liveness-readiness-probe -- Incoming Change
version: 0.1.1
appVersion: 0.2.0-develop.1
=======
version: 0.2.0-develop.2
appVersion: 0.2.0-develop.2
>>>>>>> develop -- Current Change
```

Should I go with `0.2.0-develop.3` or `0.2.1-develop` or what?

2023-11-09 10:30 UTC, pmoscode commented on .github/workflows/chart-lint-test.yml
> +  verify-helm-docs:
Sounds good. Opens for future verifiable things.

2023-11-10 07:01 UTC, borisrizov-zf commented
I believe `0.2.1-develop` is correct, as we've already deployed `0.2.0`

2023-11-10 09:01 UTC, DominikPinsel commented
> @borisrizov-zf @DominikPinsel I need help again with adjusting the chart version :D
> 
> I got the following merge conflict.
> 
> ```diff
> <<<<<<< feat/liveness-readiness-probe -- Incoming Change
> version: 0.1.1
> appVersion: 0.2.0-develop.1
> =======
> version: 0.2.0-develop.2
> appVersion: 0.2.0-develop.2
> >>>>>>> develop -- Current Change
> ```
> 
> Should I go with `0.2.0-develop.3` or `0.2.1-develop` or what?

Sorry for the late reply. The version and appversion is automatically increment to a new `<>-develop.X` version with each merged PR. You don't have to change anything there :)

2023-11-10 09:11 UTC, DominikPinsel approved these changes
Great contribution, we totally missed that :)

2023-11-14 10:38 UTC, borisrizov-zf commented
Is this ready to merge? @pmoscode @florianrusch-zf ?

2023-11-14 12:19 UTC, pmoscode commented
> Is this ready to merge? @pmoscode @florianrusch-zf? Maybe a rebase is needed?

A "yes" from my side.

2023-11-22 12:45 UTC, borisrizov-zf commented
@florianrusch-zf can you resolve the merge conflict so I can merge? (it's due to another merge I did)

2023-11-22 14:08 UTC, florianrusch-zf commented on .github/workflows/chart-lint-test.yml
> +  verify-helm-docs:
Done

2023-11-22 14:42 UTC, borisrizov-zf approved these changes

2023-11-22 14:42 UTC, merged